apiVersion : apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: todo
        image: reg.learnk8s.net/dev/mysql-spring-boot-todo/todo:v$CI_PIPELINE_ID
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: "500Mi"
          requests:
            cpu: 0.5
            memory: "500Mi"
        envEnv:
        - configMapRef:
            name: todo-config
        - configMapRef:
            name: todo-mysql-config
        - secretRef:
            name: todo-mysql-secret
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            port: http
            path: /actuator/health/readiness
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        #livenessProbe:
        #  httpGet:
        #    port: http
        #    path: /actuator/health/liveness
        #  failureThreshold: 3
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 3
        startupProbe:
          httpGet:
            port: http
            path: /actuator/health
          initialDelaySeconds: 60
          failureThreshold: 5
          periodSeconds: 10
